export const LARGE_CONTENT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus orci est, sodales non lacinia at, consectetur id lectus. Morbi euismod ante at faucibus accumsan. Aenean nec mauris urna. Sed sit amet vehicula dolor. Donec ligula lacus, consequat sit amet augue et, facilisis vulputate augue. Fusce non sem eu lectus elementum ornare. Maecenas lacus nulla, egestas ac purus ut, ultricies fermentum est. In quis lacus sodales, ullamcorper erat id, suscipit ex. Morbi auctor nisi at feugiat pretium. Suspendisse ut placerat eros, eget vehicula quam. Nunc eget ipsum a urna cursus posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent dui orci, cursus non sagittis a, vehicula molestie libero.

Nullam ante justo, varius in lobortis condimentum, egestas nec magna. Aenean ultrices nulla aliquet luctus tincidunt. Quisque pulvinar dolor at dictum blandit. Nam sodales sed nisl non tincidunt. Vivamus posuere felis eget eros euismod bibendum. Proin ut justo dapibus, ornare nisi eget, consectetur dolor. Proin iaculis eu urna vitae finibus. Ut et dolor id mi commodo ullamcorper. Integer non sem rhoncus felis viverra pharetra. Suspendisse ac egestas arcu, non lobortis eros. Aenean diam tellus, finibus a tempor quis, auctor posuere est. Maecenas eget purus ligula. Integer bibendum vehicula sapien sed gravida. Nulla ac metus dignissim, sodales purus id, semper odio.

Sed quis consectetur odio. In et nunc ullamcorper, sodales velit quis, fermentum enim. Curabitur a euismod lorem. Quisque gravida blandit sollicitudin. Nam vitae dolor dignissim, luctus urna laoreet, lacinia turpis. Vestibulum tincidunt urna nibh, a consectetur dui sagittis ut. Cras tempus tortor sit amet felis sagittis, quis sagittis nunc consequat. Fusce molestie felis in massa blandit posuere. Integer luctus id tellus ut condimentum. Curabitur eu sapien at arcu finibus lacinia quis ac tortor. Sed gravida consectetur pretium. Mauris consectetur orci a pretium sagittis.

Vivamus auctor nisl dolor, vel dignissim quam pulvinar sagittis. Ut finibus vulputate nisi, ut consectetur turpis faucibus sed. Donec consequat ante vitae ex rhoncus, ut hendrerit libero bibendum. Etiam commodo dui non magna sagittis, non faucibus erat placerat. Curabitur euismod massa elit, ut eleifend magna interdum in. Mauris suscipit efficitur nisl, placerat sodales felis commodo eget. Sed vel euismod quam, in efficitur eros. Aenean sollicitudin, purus in venenatis eleifend, dolor leo consequat arcu, eget tristique ante libero sed ante. In dapibus urna metus, feugiat mollis turpis fringilla a. Etiam eros elit, semper lacinia maximus sed, fringilla a sem. Vivamus vulputate est lacus, ut consequat nisi dictum eget. Curabitur accumsan sagittis turpis nec semper. Integer pharetra lacus nec tincidunt fringilla. Integer congue auctor sem, ac dapibus quam varius in. Sed placerat, tellus ac gravida sagittis, leo est sodales sapien, ut scelerisque nibh neque quis tellus.

Donec interdum in arcu efficitur tempus. Praesent sed volutpat erat, eu blandit ligula. Morbi dictum id mauris sed interdum. Sed id condimentum enim. Phasellus pharetra iaculis erat, non scelerisque purus maximus cursus. Nullam pharetra dictum mauris eget suscipit. Curabitur varius fermentum justo, ut consequat lacus pulvinar nec. Praesent efficitur nisl nec augue gravida vehicula. Cras non convallis nisl, nec gravida ex. Donec commodo magna dapibus ipsum consectetur laoreet.`;
